/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Rocinante.glb
Author: Rostenbach (https://sketchfab.com/Rostenbach)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocinante-886f84cae06645fbad80a12f48163bdd
Title: Rocinante
*/

// eslint-disable-next-line no-unused-vars
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rocinante.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[9625.941, 0, -1888.112]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.006}>
        <group position={[2805.067, -4401.312, 5978.204]}>
          <group position={[0, 531.627, 1063.253]} rotation={[-Math.PI, 0, 0]}>
            <mesh geometry={nodes.Material2_349.geometry} material={materials.Color_005} />
            <mesh geometry={nodes.Material3_13.geometry} material={materials.Color_007} />
          </group>
          <group position={[0, 531.627, 0]}>
            <mesh geometry={nodes.Material2_350.geometry} material={materials.Color_005} />
            <mesh geometry={nodes.Material3_14.geometry} material={materials.Color_007} />
          </group>
        </group>
        <group position={[3512.085, -4547.874, 5831.642]} scale={[1.061, 0.87, 0.87]}>
          <group position={[0, 70.866, 779.528]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_351.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_15.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_352.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_353.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_354.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_355.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_356.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_357.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_358.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_359.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_360.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_361.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_362.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_16.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_363.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_364.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_17.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_365.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_18.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_366.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_19.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_367.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_368.geometry} material={materials.edge_color303030255} />
            <lineSegments geometry={nodes.Material2_369.geometry} material={materials.edge_color198198198255} />
          </group>
          <group position={[0, 1488.189, 779.528]} rotation={[-Math.PI, 0, 0]}>
            <mesh geometry={nodes.Material2_370.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_20.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_371.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_372.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_373.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_374.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_375.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_376.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_377.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_378.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_379.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_380.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_381.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_21.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_382.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_383.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_22.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_384.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_23.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_385.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_24.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_386.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_387.geometry} material={materials.edge_color303030255} />
            <lineSegments geometry={nodes.Material2_388.geometry} material={materials.edge_color198198198255} />
          </group>
          <group position={[0, 70.866, 779.528]}>
            <mesh geometry={nodes.Material2_389.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_25.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_390.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_391.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_392.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_393.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_394.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_395.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_396.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_397.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_398.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_399.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_400.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_26.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_401.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_402.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_27.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_403.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_28.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_404.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_29.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_405.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_406.geometry} material={materials.edge_color303030255} />
            <lineSegments geometry={nodes.Material2_407.geometry} material={materials.edge_color198198198255} />
          </group>
          <group position={[0, 1488.189, 779.528]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_408.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_30.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_409.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_410.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_411.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_412.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_413.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_414.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_415.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_416.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_417.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_418.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_419.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_31.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_420.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_421.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_32.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_422.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_33.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_423.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_34.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_424.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_425.geometry} material={materials.edge_color303030255} />
            <lineSegments geometry={nodes.Material2_426.geometry} material={materials.edge_color198198198255} />
          </group>
        </group>
        <group position={[4135.526, -4468.11, 5911.406]}>
          <group position={[0, 0, 598.425]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_427.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_35.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_428.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_36.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_429.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_37.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_430.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_38.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_431.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_39.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_432.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_40.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_433.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_434.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_41.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_435.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_436.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_42.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_437.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_438.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_43.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_439.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_440.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_44.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_441.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_442.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_443.geometry} material={materials.edge_color303030255} />
          </group>
          <group position={[0, 0, 598.425]}>
            <mesh geometry={nodes.Material2_444.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_45.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_445.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_46.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_446.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_47.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_447.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_48.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_448.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_49.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_449.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_50.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_450.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_451.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_51.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_452.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_453.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_52.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_454.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_455.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_53.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_456.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_457.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_54.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_458.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_459.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_460.geometry} material={materials.edge_color303030255} />
          </group>
          <group position={[0, 1196.85, 598.425]} rotation={[-Math.PI, 0, 0]}>
            <mesh geometry={nodes.Material2_461.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_55.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_462.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_56.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_463.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_57.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_464.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_58.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_465.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_59.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_466.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_60.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_467.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_468.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_61.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_469.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_470.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_62.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_471.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_472.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_63.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_473.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_474.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_64.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_475.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_476.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_477.geometry} material={materials.edge_color303030255} />
          </group>
          <group position={[0, 1196.85, 598.425]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_478.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_65.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_479.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_66.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_480.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_67.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_481.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_68.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_482.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_69.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_483.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_70.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_484.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_485.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_71.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_486.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_487.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_72.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_488.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_489.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_73.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_490.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_491.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_74.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_492.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_493.geometry} material={materials.Color_008} />
            <lineSegments geometry={nodes.Material2_494.geometry} material={materials.edge_color303030255} />
          </group>
        </group>
        <group position={[5110.722, -4444.488, 6171.634]} scale={[0.869, 1, 0.812]}>
          <group position={[0, 0, 416.535]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_495.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_75.geometry} material={materials.Color_002} />
            <mesh geometry={nodes.Material2_496.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material3_76.geometry} material={materials.Color_002} />
          </group>
          <group position={[0, 1149.606, 416.535]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_497.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_77.geometry} material={materials.Color_002} />
            <mesh geometry={nodes.Material2_498.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material3_78.geometry} material={materials.Color_002} />
          </group>
          <group position={[0, 1149.606, 416.535]} rotation={[-Math.PI, 0, 0]}>
            <mesh geometry={nodes.Material2_499.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_500.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material3_79.geometry} material={materials.Color_002} />
          </group>
          <group position={[0, 0, 416.535]}>
            <mesh geometry={nodes.Material2_501.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_80.geometry} material={materials.Color_B02} />
          </group>
        </group>
        <group position={[5122.421, -4239.764, 5806.739]} scale={[1.1, 1, 1]}>
          <group position={[0, 740.158, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material3_83.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material3_84.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_503.geometry} material={materials.Color_008} />
          </group>
          <mesh geometry={nodes.Material3_81.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material3_82.geometry} material={materials.Color_B02} />
          <mesh geometry={nodes.Material2_502.geometry} material={materials.Color_008} />
        </group>
        <group position={[5252.034, -3869.685, 6373.902]} scale={[1, 1, 1.22]}>
          <group position={[607.874, 787.402, 111.417]} rotation={[0, 0, Math.PI / 2]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_504.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_85.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_505.geometry} material={materials.Color_008} />
          </group>
          <group position={[607.874, 787.402, 111.417]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Material2_506.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_86.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_507.geometry} material={materials.Color_008} />
          </group>
          <group position={[607.874, 787.402, 111.417]} rotation={[Math.PI, 0, Math.PI / 2]}>
            <mesh geometry={nodes.Material2_508.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_87.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_509.geometry} material={materials.Color_008} />
          </group>
          <group position={[607.874, 787.402, 111.417]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_510.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_88.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_511.geometry} material={materials.Color_008} />
          </group>
        </group>
        <group position={[5252.034, -3869.685, 6373.902]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1.22]}>
          <group position={[607.874, 787.402, 111.417]} rotation={[0, 0, Math.PI / 2]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_512.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_89.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_513.geometry} material={materials.Color_008} />
          </group>
          <group position={[607.874, 787.402, 111.417]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Material2_514.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_90.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_515.geometry} material={materials.Color_008} />
          </group>
          <group position={[607.874, 787.402, 111.417]} rotation={[Math.PI, 0, Math.PI / 2]}>
            <mesh geometry={nodes.Material2_516.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_91.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_517.geometry} material={materials.Color_008} />
          </group>
          <group position={[607.874, 787.402, 111.417]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_518.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material3_92.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_519.geometry} material={materials.Color_008} />
          </group>
        </group>
        <group position={[7361.463, -3549.72, 6195.858]} rotation={[0, 0, -Math.PI]} scale={[-0.995, 0.902, 1.83]}>
          <mesh geometry={nodes.Material2_520.geometry} material={materials.Color_007} position={[0, 0, 21.26]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_521.geometry} material={materials.Color_007} position={[0, 0, 21.26]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group position={[3439.432, -4449.969, 5929.547]} scale={[0.888, 0.921, 0.921]}>
          <group position={[43.307, 629.921, 629.921]} rotation={[-Math.PI, 0, 0]}>
            <mesh geometry={nodes.Material2_522.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_523.geometry} material={materials.Color_004} />
          </group>
          <group position={[43.307, 629.921, 629.921]}>
            <mesh geometry={nodes.Material2_524.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_525.geometry} material={materials.Color_004} />
          </group>
          <group position={[43.307, 629.921, 629.921]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_526.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_527.geometry} material={materials.Color_004} />
          </group>
          <group position={[43.307, 629.921, 629.921]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_528.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_529.geometry} material={materials.Color_004} />
          </group>
        </group>
        <group position={[3229.715, -4106.431, 6942.553]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_530.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_531.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_532.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_533.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[3229.715, -4106.431, 6076.922]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_534.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_535.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_536.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_537.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[3229.715, -4302.5, 6267.087]} rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_538.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_539.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_540.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_541.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[3229.715, -3436.476, 6267.087]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_542.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_543.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_544.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_545.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[3194.262, -4351.772, 6663.108]} rotation={[Math.PI / 4, 0, 0]} scale={[1.133, 1, 1.12]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_546.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_547.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_548.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_549.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[3196.88, -3386.424, 6663.27]} rotation={[-Math.PI / 4, 0, -Math.PI]} scale={[-1.133, 1, 1.12]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_550.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_551.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_552.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_553.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[3196.88, -4356.762, 6360.207]} rotation={[2.356, 0, -Math.PI]} scale={[-1.133, 1, 1.12]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_554.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_555.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_556.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_557.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[3196.88, -3389.737, 6353.078]} rotation={[-2.356, 0, 0]} scale={[1.133, 1, 1.12]}>
          <group scale={[1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_558.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_559.geometry} material={materials.Color_006} />
          </group>
          <group position={[0, 473.491, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.88, 1]}>
            <mesh geometry={nodes.Material2_560.geometry} material={materials.Color_006} />
            <mesh geometry={nodes.Material2_561.geometry} material={materials.Color_006} />
          </group>
        </group>
        <group position={[4146.993, -4119.606, 7108.256]}>
          <mesh geometry={nodes.Material2_562.geometry} material={materials.Color_004} scale={[1, 0.92, 1]} />
          <mesh geometry={nodes.Material2_563.geometry} material={materials.Color_004} position={[0, 499.842, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.92, 1]} />
        </group>
        <group position={[4146.993, -4119.606, 5911.406]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material2_564.geometry} material={materials.Color_004} scale={[1, 0.92, 1]} />
          <mesh geometry={nodes.Material2_565.geometry} material={materials.Color_004} position={[0, 499.842, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.92, 1]} />
        </group>
        <group position={[6224.946, -4678.74, 6373.902]} rotation={[Math.PI / 2, 0, 0]} scale={[-1, 0.544, 1]}>
          <mesh geometry={nodes.Material2_566.geometry} material={materials.Color_004} scale={[1, 0.92, 1]} />
          <mesh geometry={nodes.Material2_567.geometry} material={materials.Color_004} position={[0, 499.842, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.92, 1]} />
        </group>
        <group position={[6224.946, -3059.093, 6373.902]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1, 0.544, 1]}>
          <mesh geometry={nodes.Material2_568.geometry} material={materials.Color_004} scale={[1, 0.92, 1]} />
          <mesh geometry={nodes.Material2_569.geometry} material={materials.Color_004} position={[0, 499.842, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.92, 1]} />
        </group>
        <group position={[7819.898, -4286.276, 6391.572]} rotation={[Math.PI / 2, 0.185, 0]} scale={[-0.85, 0.473, 1]}>
          <mesh geometry={nodes.Material2_570.geometry} material={materials.Color_004} scale={[1, 0.92, 1]} />
          <mesh geometry={nodes.Material2_571.geometry} material={materials.Color_004} position={[0, 499.842, 0]} rotation={[0, 0, Math.PI]} scale={[-1, 0.92, 1]} />
        </group>
        <group position={[7819.898, -3453.094, 6628.089]} rotation={[-Math.PI / 2, 0.201, 0]} scale={[-0.85, 0.473, 1]}>
          <mesh geometry={nodes.Material2_572.geometry} material={materials.Color_004} scale={[1, 0.92, 1]} />
          <mesh geometry={nodes.Material2_573.geometry} material={materials.Color_004} position={[0, 499.842, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.92, 1]} />
        </group>
        <group position={[7819.898, -3975.777, 6647.173]} scale={[0.87, 1, 0.89]}>
          <group position={[0, -1485.64, 0]}>
            <mesh geometry={nodes.Material2_574.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_575.geometry} material={materials.Color_007} />
            <mesh geometry={nodes.Material3_93.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_94.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_576.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_577.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_95.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_578.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_96.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_579.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_97.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_580.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_98.geometry} material={materials.Color_009} />
          </group>
          <group position={[0, 1697.825, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_581.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_582.geometry} material={materials.Color_007} />
            <mesh geometry={nodes.Material3_99.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_100.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_583.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_584.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_101.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_585.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_102.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_586.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_103.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_587.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_104.geometry} material={materials.Color_009} />
          </group>
        </group>
        <group position={[7825.461, -3975.777, 6464.77]} rotation={[-Math.PI, -0.188, -Math.PI]} scale={[-0.87, 1, 0.89]}>
          <group position={[0, -1485.64, 0]}>
            <mesh geometry={nodes.Material2_588.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_589.geometry} material={materials.Color_007} />
            <mesh geometry={nodes.Material3_105.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_106.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_590.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_591.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_107.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_592.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_108.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_593.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_109.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_594.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_110.geometry} material={materials.Color_009} />
          </group>
          <group position={[0, 1697.825, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_595.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_596.geometry} material={materials.Color_007} />
            <mesh geometry={nodes.Material3_111.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_112.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_597.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_598.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_113.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_599.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_114.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_600.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_115.geometry} material={materials.Color_009} />
            <mesh geometry={nodes.Material2_601.geometry} material={materials.material} />
            <mesh geometry={nodes.Material3_116.geometry} material={materials.Color_009} />
          </group>
        </group>
        <group position={[5110.722, -4747.244, 6483.059]}>
          <mesh geometry={nodes.Material2_602.geometry} material={materials.Color_004} position={[0, 0, 26.772]} />
          <mesh geometry={nodes.Material2_603.geometry} material={materials.Color_004} position={[0, 0, 26.772]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]} />
        </group>
        <group position={[5110.722, -2991.445, 6483.059]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material2_604.geometry} material={materials.Color_004} position={[0, 0, 26.772]} />
          <mesh geometry={nodes.Material2_605.geometry} material={materials.Color_004} position={[0, 0, 26.772]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]} />
        </group>
        <group position={[6313.693, -4693.02, 6409.839]} scale={[0.85, 1, 1]}>
          <mesh geometry={nodes.Material2_606.geometry} material={materials.Color_004} position={[0, 0, 99.992]} />
          <mesh geometry={nodes.Material2_607.geometry} material={materials.Color_004} position={[0, 0, 99.992]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]} />
        </group>
        <group position={[6313.693, -3045.669, 6409.839]} rotation={[0, 0, -Math.PI]} scale={[-0.85, 1, 1]}>
          <mesh geometry={nodes.Material2_608.geometry} material={materials.Color_004} position={[0, 0, 99.992]} />
          <mesh geometry={nodes.Material2_609.geometry} material={materials.Color_004} position={[0, 0, 99.992]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]} />
        </group>
        <group position={[5110.722, -4211.855, 6717.318]}>
          <group position={[0, -20.035, 130.709]}>
            <mesh geometry={nodes.Material2_610.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_611.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_612.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material3_117.geometry} material={materials.Color_002} />
          </group>
          <group position={[0, 704.374, 130.709]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_613.geometry} material={materials.Color_008} />
            <mesh geometry={nodes.Material2_614.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_615.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material3_118.geometry} material={materials.Color_002} />
          </group>
        </group>
        <group position={[6668.63, -4218.15, 6734.707]}>
          <group position={[-167.271, 696.929, 0]} rotation={[0, 0, -Math.PI]} scale={[-1.06, 1, 1]}>
            <mesh geometry={nodes.Material3_119.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material3_120.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_616.geometry} material={materials.Color_008} />
          </group>
          <group position={[-167.271, 0, 0]} scale={[1.06, 1, 1]}>
            <mesh geometry={nodes.Material3_121.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material3_122.geometry} material={materials.Color_B02} />
            <mesh geometry={nodes.Material2_617.geometry} material={materials.Color_008} />
          </group>
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_618.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_619.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_620.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_621.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_622.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_623.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_624.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_625.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_626.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_627.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_628.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_629.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_630.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_631.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_632.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_633.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_634.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_635.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_636.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_637.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_638.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_639.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_640.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_641.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_642.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_643.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_644.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_645.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_646.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_647.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3935.827, 6509.831]}>
          <mesh geometry={nodes.Material2_648.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_649.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3803.543, 6509.831]} rotation={[Math.PI, 0, 0]}>
          <mesh geometry={nodes.Material2_650.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_651.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3869.685, 6575.972]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Material2_652.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_653.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3869.685, 6443.689]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Material2_654.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_655.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3916.454, 6463.061]} rotation={[Math.PI / 4, 0, 0]}>
          <mesh geometry={nodes.Material2_656.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_657.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3822.916, 6463.061]} rotation={[2.356, 0, 0]}>
          <mesh geometry={nodes.Material2_658.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_659.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3916.454, 6556.6]} rotation={[-Math.PI / 4, 0, 0]}>
          <mesh geometry={nodes.Material2_660.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_661.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[2751.917, -3822.916, 6556.6]} rotation={[-2.356, 0, 0]}>
          <mesh geometry={nodes.Material2_662.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Material2_663.geometry} material={materials.Color_005} position={[-25.591, 66.142, 0]} />
        </group>
        <group position={[5110.722, -4579.425, 6199.489]} scale={[1.279, 1, 0.759]}>
          <group position={[219.074, 0, 0]}>
            <mesh geometry={nodes.Material2_667.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_668.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_669.geometry} material={materials.Color_004} />
          </group>
          <mesh geometry={nodes.Material2_664.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_665.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_666.geometry} material={materials.Color_004} />
        </group>
        <group position={[5112.297, -3167.074, 6199.489]} rotation={[0, 0, -Math.PI]} scale={[-1.279, 1, 0.759]}>
          <group position={[219.074, 0, 0]}>
            <mesh geometry={nodes.Material2_673.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_674.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_675.geometry} material={materials.Color_004} />
          </group>
          <mesh geometry={nodes.Material2_670.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_671.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_672.geometry} material={materials.Color_004} />
        </group>
        <group position={[8150.252, -3987.776, 6478.439]} scale={[1.06, 1, 1]}>
          <group position={[0, 118.091, 0]}>
            <mesh geometry={nodes.Material2_676.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_677.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_678.geometry} material={materials.Color_009} />
          </group>
          <group position={[0, 118.091, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Material2_679.geometry} material={materials.Color_004} />
            <mesh geometry={nodes.Material2_680.geometry} material={materials.material} />
            <mesh geometry={nodes.Material2_681.geometry} material={materials.Color_009} />
          </group>
        </group>
        <group position={[6999.225, -4444.488, 6509.831]}>
          <mesh geometry={nodes.Material3.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material3_1.geometry} material={materials.Color_B02} />
          <mesh geometry={nodes.Material2.geometry} material={materials.Color_002} />
          <mesh geometry={nodes.Material2_1.geometry} material={materials.Color_008} />
        </group>
        <group position={[6999.225, -3294.882, 6509.831]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material3_2.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material3_3.geometry} material={materials.Color_B02} />
          <mesh geometry={nodes.Material2_2.geometry} material={materials.Color_002} />
          <mesh geometry={nodes.Material2_3.geometry} material={materials.Color_008} />
        </group>
        <group position={[6999.225, -4444.488, 6267.135]}>
          <mesh geometry={nodes.Material2_4.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material3_4.geometry} material={materials.Color_B02} />
        </group>
        <group position={[6999.225, -3294.882, 6267.135]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material3_5.geometry} material={materials.Color_B02} />
        </group>
        <group position={[6478.399, -4019.291, 6848.027]}>
          <mesh geometry={nodes.Material2_6.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_7.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material3_6.geometry} material={materials.Color_002} />
          <mesh geometry={nodes.Material2_8.geometry} material={materials.Color_006} />
        </group>
        <group position={[6478.399, -3720.079, 6848.027]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material2_9.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_10.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material3_7.geometry} material={materials.Color_002} />
          <mesh geometry={nodes.Material2_11.geometry} material={materials.Color_006} />
        </group>
        <group position={[6384.453, -4019.291, 6144.075]}>
          <mesh geometry={nodes.Material2_12.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material3_8.geometry} material={materials.Color_002} />
          <lineSegments geometry={nodes.Material2_13.geometry} material={materials.edge_color198198198255} />
        </group>
        <group position={[6384.453, -3720.079, 6144.075]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material2_14.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material3_9.geometry} material={materials.Color_002} />
          <lineSegments geometry={nodes.Material2_15.geometry} material={materials.edge_color198198198255} />
        </group>
        <group position={[7361.463, -4195.276, 6195.858]}>
          <mesh geometry={nodes.Material2_16.geometry} material={materials.Color_007} />
          <mesh geometry={nodes.Material3_10.geometry} material={materials.Color_002} />
        </group>
        <group position={[4297.318, -3968.916, 7163.387]} scale={0.722}>
          <mesh geometry={nodes.Material2_17.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_18.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_19.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_20.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_21.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_22.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_23.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_24.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_25.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_26.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_27.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_28.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_29.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_30.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_31.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_32.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_33.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_34.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_35.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_36.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_37.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_38.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_39.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_40.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_41.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_42.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_43.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_44.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_45.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_46.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_47.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_48.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_49.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_50.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_51.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_52.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_53.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_54.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_55.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_56.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_57.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_58.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_59.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_60.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_61.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_62.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_63.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_64.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_65.geometry} material={materials.Color_003} />
          <lineSegments geometry={nodes.Material2_66.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_67.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_68.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_69.geometry} material={materials.edge_color170170170255} />
        </group>
        <group position={[4297.318, -3968.916, 5856.275]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.722, 0.722, 0.722]}>
          <mesh geometry={nodes.Material2_70.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_71.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_72.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_73.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_74.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_75.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_76.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_77.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_78.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_79.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_80.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_81.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_82.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_83.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_84.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_85.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_86.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_87.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_88.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_89.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_90.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_91.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_92.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_93.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_94.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_95.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_96.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_97.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_98.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_99.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_100.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_101.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_102.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_103.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_104.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_105.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_106.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_107.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_108.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_109.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_110.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_111.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_112.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_113.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_114.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_115.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_116.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_117.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_118.geometry} material={materials.Color_003} />
          <lineSegments geometry={nodes.Material2_119.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_120.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_121.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_122.geometry} material={materials.edge_color170170170255} />
        </group>
        <group position={[6074.62, -4733.871, 6425.404]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.607, 0.607, 0.607]}>
          <mesh geometry={nodes.Material2_123.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_124.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_125.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_126.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_127.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_128.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_129.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_130.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_131.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_132.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_133.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_134.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_135.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_136.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_137.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_138.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_139.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_140.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_141.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_142.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_143.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_144.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_145.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_146.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_147.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_148.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_149.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_150.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_151.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_152.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_153.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_154.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_155.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_156.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_157.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_158.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_159.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_160.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_161.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_162.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_163.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_164.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_165.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_166.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_167.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_168.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_169.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_170.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_171.geometry} material={materials.Color_003} />
          <lineSegments geometry={nodes.Material2_172.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_173.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_174.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_175.geometry} material={materials.edge_color170170170255} />
        </group>
        <group position={[6074.62, -3003.962, 6425.404]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.607}>
          <mesh geometry={nodes.Material2_176.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_177.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_178.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_179.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_180.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_181.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_182.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_183.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_184.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_185.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_186.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_187.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_188.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_189.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_190.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_191.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_192.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_193.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_194.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_195.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_196.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_197.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_198.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_199.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_200.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_201.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_202.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_203.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_204.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_205.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_206.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_207.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_208.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_209.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_210.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_211.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_212.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_213.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_214.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_215.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_216.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_217.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_218.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_219.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_220.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_221.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_222.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_223.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_224.geometry} material={materials.Color_003} />
          <lineSegments geometry={nodes.Material2_225.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_226.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_227.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_228.geometry} material={materials.edge_color170170170255} />
        </group>
        <group position={[7631.906, -4412.542, 6437.211]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.522, 0.522, 0.522]}>
          <mesh geometry={nodes.Material2_229.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_230.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_231.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_232.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_233.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_234.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_235.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_236.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_237.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_238.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_239.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_240.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_241.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_242.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_243.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_244.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_245.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_246.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_247.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_248.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_249.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_250.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_251.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_252.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_253.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_254.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_255.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_256.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_257.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_258.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_259.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_260.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_261.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_262.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_263.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_264.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_265.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_266.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_267.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_268.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_269.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_270.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_271.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_272.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_273.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_274.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_275.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_276.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_277.geometry} material={materials.Color_003} />
          <lineSegments geometry={nodes.Material2_278.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_279.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_280.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_281.geometry} material={materials.edge_color170170170255} />
        </group>
        <group position={[7631.906, -3318.493, 6582.264]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.522, 0.522, 0.522]}>
          <mesh geometry={nodes.Material2_282.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_283.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_284.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_285.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_286.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_287.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_288.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_289.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_290.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_291.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_292.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_293.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_294.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_295.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_296.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_297.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_298.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_299.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_300.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_301.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_302.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_303.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_304.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_305.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_306.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_307.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_308.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_309.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_310.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_311.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_312.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_313.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_314.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_315.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_316.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_317.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_318.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_319.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_320.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_321.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_322.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_323.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_324.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_325.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_326.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_327.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_328.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_329.geometry} material={materials.Color_003} />
          <mesh geometry={nodes.Material2_330.geometry} material={materials.Color_003} />
          <lineSegments geometry={nodes.Material2_331.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_332.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_333.geometry} material={materials.edge_color170170170255} />
          <lineSegments geometry={nodes.Material2_334.geometry} material={materials.edge_color170170170255} />
        </group>
        <group position={[7904.691, -4201.377, 6457.994]}>
          <mesh geometry={nodes.Material2_335.geometry} material={materials.Color_007} />
          <mesh geometry={nodes.Material2_336.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_337.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_338.geometry} material={materials.Color_009} />
        </group>
        <group position={[7904.691, -3537.197, 6457.994]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material2_339.geometry} material={materials.Color_007} />
          <mesh geometry={nodes.Material2_340.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_341.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_342.geometry} material={materials.Color_009} />
        </group>
        <group position={[6318.644, -4211.855, 6717.318]}>
          <mesh geometry={nodes.Material2_343.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_344.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_345.geometry} material={materials.Color_006} />
          <mesh geometry={nodes.Material3_11.geometry} material={materials.material} />
        </group>
        <group position={[6271.329, -4207.918, 6312.196]} rotation={[-Math.PI, 0.08, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Material2_346.geometry} material={materials.Color_008} />
          <mesh geometry={nodes.Material2_347.geometry} material={materials.Color_004} />
          <mesh geometry={nodes.Material2_348.geometry} material={materials.Color_006} />
          <mesh geometry={nodes.Material3_12.geometry} material={materials.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Rocinante.glb')
